# Generated by Django 3.2 on 2022-04-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractHuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('abstracthuman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstracthuman')),
                ('address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
            bases=('main.abstracthuman',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('abstracthuman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstracthuman')),
                ('work_position', models.CharField(max_length=50)),
                ('work_experience', models.DateField()),
            ],
            bases=('main.abstracthuman',),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
        migrations.CreateModel(
            name='VIPCustomer',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.customer')),
                ('vip_status_start', models.DateField()),
                ('donation_amount', models.CharField(max_length=999999)),
            ],
            bases=('main.customer',),
        ),
        migrations.AddField(
            model_name='project',
            name='worker',
            field=models.ManyToManyField(through='main.Membership', to='main.Worker'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=14)),
                ('card_id', models.CharField(max_length=6)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
    ]
